### ISSUE TITLE
dependencies are not updating watchify

### ISSUE THREAD

**Issue by contra** [DamonOehlman/stylify#11]
i dont know where this one should be fixed - if you update a mixin that is used by a stylus file which is required by browserify it will not trigger a watchify update

**Comment by contra** [comment]
here is how jade fixes this:

https://github.com/domenic/jadeify/blob/master/lib/jadeify.js#L29

they get a list of the files that the file being compiled is dependent on and then emit 'file' events for each one which lets browserify and watchify know to track them

**Comment by contra** [comment]
I fixed this in my branch via https://github.com/contra/stylify/commit/61d1cd72fe68064bfbf4e3ee9f14f2b64ac6c7e9

**Comment by DamonOehlman** [comment]
If you are happy with the approach, then I'm all for merging.  I'll give you npm publish access too :)

**Comment by appedemic** [comment]
This is not in the npm version (1.2.0) yet? Would be very useful.

**Comment by DamonOehlman** [comment]
@appedemic Good point, thanks.

@contra any one of us can push the package to the npm registry as far as can tell.  Did you want to version and publish?  If not I'm happy to :)

**Comment by contra** [comment]
@DamonOehlman on the road right now, you can do it

**Comment by DamonOehlman** [comment]
@contra cool mate - will do.  Thanks again for landing the change.

**Comment by DamonOehlman** [comment]
Published `1.3.0` (near enough to a new feature to go with the minor release bump for me).

+@appdemic
