### ISSUE TITLE
Allow using `nib` from the command line

### ISSUE THREAD

**Issue by rstacruz** [DamonOehlman/stylify#12]
It would be nice to be able to do:

```
browserify -t [ stylify --use nib ]
```

...and have nib be automatically picked up. This currently won't work (the `use` option expects an actual plugin, not a string).

**Comment by rstacruz** [comment]
Also, #5 - it would be nice to document CLI usage!

**Comment by contra** [comment]
duplicate of https://github.com/DamonOehlman/stylify/issues/9

**Comment by rstacruz** [comment]
Thanks, I'm a little unfamiliar with the code of stylify at the moment, but does this mean I can actually do `--use modulename`?

How does that factor into nib, which needs `use: require("nib")()` instead of `use: require("nib")` ?

**Comment by rstacruz** [comment]
Okay, just used your branch and indeed, it's as easy as `-t [ stylify --use nib ]` ;)
