### ISSUE TITLE
Lodash is big

### ISSUE THREAD

**Issue by hij1nx** [DamonOehlman/stylify#3]
Would you consider just including the individual lodash modules that are used in this lib?

**Comment by jdalton** [comment]
[lodash v3](https://github.com/lodash/lodash/releases/tag/3.0.0) has lots of improvements. You can even require just methods you want using something like `require('lodash/lang/clone')`.

**Comment by DamonOehlman** [comment]
@jdalton nice to hear mate - being able to cherrypick stuff out makes a big difference to me :)
