### ISSUE TITLE
How to configure Stylify (Gulp)

### ISSUE THREAD

**Issue by antoniobrandao** [DamonOehlman/stylify#4]
Hello, I'm having difficulties configuring Stylify with Browserify.

I added the transform in my package.json like this and it works fine, without extras like source maps or compression

    "browserify": {
      "transform": [
        "cssify",
        "stylify",
        "brfs"
      ]
    },

But I really need these following thingies in my Stylus code:

    [ jeet(), rupture(), typographic(), axis(), autoprefixer({ browsers: ['ie 7', 'ie 8'] })] } ]

In the docs there is an example as follows:

    var nib = require 'nib';
    var browserify = require 'browserify';
    
    // create a browserify bundle
    var bundle = browserify({ ... });
    
    // register the stylify tranforms with options
    bundle.transform('stylify', {
      use: [ nib() ],
      set: { compress: true }
    });

This is how my working Browserify task looks like:

    gulp.task('js', ['environmentCheck'], function() {
    
      var bundler = browserify({
        // Required watchify args
        cache: {}, packageCache: {}, fullPaths: true,
        // Browserify Options
        entries:    ['./core/js/core.js'],
        extensions: ['.coffee', '.hbs'],
        debug:      global.ENV === 'development'
      });
    
      var bundle = function() 
      {
        bundleLogger.start();
    
        return bundler
          .bundle()
          .on('error', handleErrors)
          .pipe(source('bundle.js'))
          // remove console.logs and such
          .pipe(gulpif( global.ENV === 'production', streamify( strip() )))
          // uglify JS and obfuscate in produciton mode only
          .pipe(gulpif( global.ENV === 'production', streamify(uglify({ mangle: global.ENV === 'production' }))))
          .pipe(print())
          .pipe(gulp.dest(global.outputDir + datapaths.dataPath + '/js'))
          // .pipe(connect.reload())
          .on('end', bundleLogger.end);
      };
    
      return bundle();
    });

If I add the transform as documented (I think) it looks like this (notice the bundler.transform())

    var jeet          = require("jeet");

    gulp.task('js', ['environmentCheck'], function() {
    
      var bundler = browserify({
        // Required watchify args
        cache: {}, packageCache: {}, fullPaths: true,
        // Browserify Options
        entries:    ['./core/js/core.js'],
        extensions: ['.coffee', '.hbs'],
        debug:      global.ENV === 'development'
      });
    
      bundler.transform('stylify', {
        use: [ jeet() ],
        set: { compress: true }
      });
    
      var bundle = function() 
      {
        bundleLogger.start();
    
        return bundler
          .bundle()
          .on('error', handleErrors)
          .pipe(source('bundle.js'))
          // remove console.logs and such
          .pipe(gulpif( global.ENV === 'production', streamify( strip() )))
          // uglify JS and obfuscate in produciton mode only
          .pipe(gulpif( global.ENV === 'production', streamify(uglify({ mangle: global.ENV === 'production' }))))
          .pipe(print())
          .pipe(gulp.dest(global.outputDir + datapaths.dataPath + '/js'))
          // .pipe(connect.reload())
          .on('end', bundleLogger.end);
      };
    
      return bundle();
    });

But I get an error which is this:

    Error: /Users/antoniobrandao/WEBROOT/vvfamous/src/stylus/pages/index.styl:1:8
       1| module.exports = ""
    -------------^
       2|
    
    module has no property .exports
     while parsing file: /Users/antoniobrandao/WEBROOT/vvfamous/src/stylus/pages/index.styl

To give you a complete clear idea of what I want from my Stylus processing, I show you my current stylus task which carries all the options I need:

    gulp.task('stylus', ['environmentCheck'], function () 
    {  
      gulp.src( datapaths.cssSrcPath )
      .pipe( plumber( handleErrors ) )
      .pipe(stylus({ 
        compress: global.ENV === 'production',
        use:[ 
            jeet(),
            rupture(), 
            typographic(), 
            axis(), 
            autoprefixer({ browsers: ['ie 7', 'ie 8'] })
          ],
          sourcemap: { inline: global.ENV === 'development' } 
      }))
      .pipe(print())
      .pipe(gulp.dest(global.outputDir + datapaths.dataPath + '/css'));
      // .pipe(gulpif( global.isWatching === true, connect.reload() ));
    });

Final note:

The error is the same whether I I am requiring my root Stylus file with:

    var insertCss       = require('insert-css');
    insertCss(require('../../stylus/pages/index.styl'));

Or with 

    require('../../stylus/pages/index.styl');

I also tried using stylify configuration directly in package.json as follows to no avail:

    "stylify": {
        "use"    : [ "jeet", "rupture", "typographic" ]
    },

**Comment by DavidRivers** [comment]
Hey, @antoniobrandao. Did you ever solve this problem? I'm trying to do the same thing and am unsure of how to consume stylus dependencies while also using stylify.

**Comment by antoniobrandao** [comment]
Oh yeah, great that you called my attention to this, I forgot to post my solution and close this. I did solve my problem. I mean I got it to work. But not in perfection, as I still can't see source maps in the devtools. But I can live with it for now. Please refer to this question on StackOverflow http://stackoverflow.com/questions/27974446/how-to-get-source-maps-with-stylify-and-insert-css and if you manage to get source maps working *please* let me know :)
