### ISSUE TITLE
cant pass options other than paths via package

### ISSUE THREAD

**Issue by contra** [DamonOehlman/stylify#9]
https://github.com/DamonOehlman/stylify/blob/master/index.js#L18

opening an issue for this one

**Comment by contra** [comment]
I fixed this by resolving the use args https://github.com/contra/stylify/blob/resolve-uses/index.js#L59

and adding this https://github.com/contra/stylify/blob/resolve-uses/index.js#L41

**Comment by rstacruz** [comment]
Let's get that merged!

**Comment by contra** [comment]
My branch is a total rewrite - @DamonOehlman you cool with that?

**Comment by DamonOehlman** [comment]
Sure thing - if it's a step forward I'm all for it, so yep go for it!

**Comment by felixhageloh** [comment]
anything needed to get this merged?  I have some time to work on this again.

**Comment by DamonOehlman** [comment]
@felixhageloh yeah if you have some time to merge that would be awesome :)

**Comment by felixhageloh** [comment]
sorry, got really busy again after all. I'll see if I can get this merged this weekend! 
Slightly random, but what do you guys think abut this https://speakerdeck.com/vjeux/react-css-in-js, compared to using something like stylify?
